In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.93772907 -1.63069886 -0.20138463 -0.25151955  0.46509899]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 1.93772907 -1.63069886 -0.20138463 -0.25151955  0.46509899]


In [5]:
print(np.dot(a, a.T))

6.73410764024


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[-0.19966704]
 [ 0.88559922]
 [-1.58717144]
 [-0.93463107]
 [-0.59551277]]


In [8]:
print(a.T)

[[-0.19966704  0.88559922 -1.58717144 -0.93463107 -0.59551277]]


In [9]:
print(np.dot(a, a.T))

[[ 0.03986693 -0.17682497  0.31690582  0.18661502  0.11890427]
 [-0.17682497  0.78428599 -1.40559779 -0.82770855 -0.52738565]
 [ 0.31690582 -1.40559779  2.51911318  1.48341975  0.94518087]
 [ 0.18661502 -0.82770855  1.48341975  0.87353524  0.55658474]
 [ 0.11890427 -0.52738565  0.94518087  0.55658474  0.35463546]]
